paths:
  depth_folder: /Users/josedlh/Documents/demo/sfm_1_output/02_sfm/depth_pruned
  images_dir: /Users/josedlh/Documents/demo/sfm_1_output/02_sfm/images_pruned
  detections_json: /Users/josedlh/Documents/demo/sfm_1_output/detections/detections.json
  poses_file: /Users/josedlh/Documents/demo/sfm_1_output/02_sfm/poses_mm_yup.txt
  ceres_solver_bin: /Users/josedlh/new_ba/build/bundle_adjustment
  refined_poses_file: refined_poses.txt
  output_dir: /Users/josedlh/Documents/demo/sfm_1_output/03_tracking
  tracks_json: tracks.json
  cleaned_tracks_json: tracks_cleaned.json
  ceres_dir: ceres
  post_delta_json: post_delta.json
  merged_tracks_json: merged_tracks.json
thresholds:
  iou_thresh: 0.15
  outlier_delta: 5
  min_track_len: 4
  min_consecutive: 4
clustering:
  voxel_size: 5
  dbscan_eps: 15
  dbscan_samples: 10
  min_cluster_detections: 4
deduplication:
  max_centroid_distance_mm: 50.0
  min_mask_iou: 0.1
image:
  width: 1920
  height: 1200
intrinsics:
  fx: 1272.44
  fy: 1272.67
  cx: 920.062
  cy: 618.949
